### ISSUE TITLE
Validate that producer is defined when including KafkaSource

### ISSUE THREAD

**Issue by dorner** [flipp-oss/deimos#90]
When a class includes KafkaSource but doesn't define a producer (by overriding `kafka_producers` or `kafka_producer`), we get a `SystemStackError: stack level too deep`. We should instead add a check to see if both methods are nil and if so, raise an error.

**Comment by eduardopoleoflipp** [comment]
What do you mean by:

> check to see if both methods are nil

Do we mean to have some sort of top level validation at the parent class so that we fail explicitly in case we subclasses doing things like this:

```ruby
def self.kafka_producers
end
```

The `SystemStackError: stack level too deep` is happening because [here](https://github.com/flipp-oss/deimos/blob/master/lib/deimos/kafka_source.rb#L68) the owner that gets returned is `Deimos::KafkaSource::ClassMethods` and not `Deimos::KafkaSource` . I can put a patch for this but want to make sure I fully understand the bug description.

**Comment by dorner** [comment]
Honestly this was made as a backwards compatibility thing and we really should be moving all code to be `self.kafka_producers`. I'd actually be OK with removing the parent method `self.kafka_producer` entirely and changing this to a `respond_to?` check, logging a deprecation and removing calling the method in a future release.
